### ISSUE TITLE
Other User Issue DD DT

### ISSUE THREAD

**Issue by denisdenisov** [denistsuman/public-test#12]
DenisTsuman edited

--
Source: https://mail.missiveapp.com/#inbox/conversations/7dbf78a5-1730-4451-afb4-38fe35614f29

**Comment by denisdenisov** [comment]
Missive conversation: https://mail.missiveapp.dev/#inbox/conversations/7dbf78a5-1730-4451-afb4-38fe35614f29

**Comment by denistsuman** [comment]
Missive conversation: https://mail.missiveapp.dev/#inbox/conversations/7dbf78a5-1730-4451-afb4-38fe35614f29
